builds:
  -
    env:
      - GO111MODULE=on
    binary: pwg
    main: ./cmd/pwg/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
    ldflags:
      - -s -w -X 'main.Name=pwg' -X 'main.Version=v{{.Version}}'
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
release:
  github:
    owner: saihon
    name: pwg
  draft: true